spring.application.name=service

spring.datasource.url=jdbc:postgresql://db:5432/ecopoint
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true


ecopoint.mqtt.broker=tcp://broker:1883
ecopoint.mqtt.clientId=spring-ecopoint-backend
ecopoint.mqtt.username=
ecopoint.mqtt.password=

ecopoint.topics.subFilter=ecopoint/+/events